"""
https://leetcode.com/problems/find-the-difference/

389. Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
"""


class WordDifference:
    def findTheDifference(self, s: str, t: str) -> str:
        word = sorted(t)
        for ch in s: word.remove(ch)
        return word[0]


if __name__ == '__main__':
    s = "abcd"
    t = "adcbe"
    word_difference = WordDifference()
    print(word_difference.findTheDifference(s, t))
